"""
Source match model for the SpyDrop service.

SourceMatch connects a competitor's product to potential suppliers,
showing where the product can be sourced from and at what cost.

For Developers:
    Source matches are generated by the `find_product_sources` task.
    The `confidence_score` (0.0-1.0) indicates how likely the match is
    correct. `margin_percent` is calculated as:
    ((competitor_price - source_cost) / competitor_price) * 100

For QA Engineers:
    Test source finding via POST /api/v1/sources/{product_id}/find.
    Verify confidence scores are between 0 and 1.
    Check margin calculations are correct.

For Project Managers:
    Source matching is a premium feature that helps users find suppliers
    for products their competitors are selling, enabling them to compete
    by sourcing the same or similar products.

For End Users:
    Find where competitors source their products and calculate your
    potential profit margin if you sell the same items.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class SourceMatch(Base):
    """
    A potential supplier match for a competitor's product.

    Attributes:
        id: Unique identifier (UUID v4).
        competitor_product_id: Foreign key to the matched CompetitorProduct.
        supplier: Supplier name (e.g., 'AliExpress', 'DHgate', '1688').
        supplier_url: Direct URL to the supplier's product listing.
        cost: Supplier's price for the product.
        currency: Currency code for the cost (default 'USD').
        confidence_score: Match confidence (0.0 to 1.0).
        margin_percent: Calculated profit margin percentage.
        created_at: Record creation timestamp.
        product: Related CompetitorProduct record.
    """

    __tablename__ = "source_matches"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    competitor_product_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("competitor_products.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    supplier: Mapped[str] = mapped_column(String(255), nullable=False)
    supplier_url: Mapped[str] = mapped_column(String(2048), nullable=False)
    cost: Mapped[float | None] = mapped_column(Float, nullable=True)
    currency: Mapped[str] = mapped_column(
        String(10), default="USD", nullable=False
    )
    confidence_score: Mapped[float] = mapped_column(
        Float, default=0.0, nullable=False
    )
    margin_percent: Mapped[float | None] = mapped_column(Float, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    # Relationships
    product: Mapped["CompetitorProduct"] = relationship(
        "CompetitorProduct", back_populates="source_matches", lazy="selectin"
    )


from app.models.competitor import CompetitorProduct  # noqa: E402
