"""add_order_tracking_fields

Revision ID: 067876d001ca
Revises: 08742fa19426
Create Date: 2026-02-09 16:59:07.820069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067876d001ca'
down_revision: Union[str, Sequence[str], None] = '08742fa19426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('carrier', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'carrier')
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
