"""Store theme database model.

Defines the ``store_themes`` table for per-store visual customization.
Each store can have multiple themes (presets + custom) with one active at a time.
Theme configuration includes colors, typography, styles, and page blocks.

**For Developers:**
    Import this model via ``app.models`` for Alembic migration autogenerate.
    The ``colors``, ``typography``, ``styles``, and ``blocks`` columns are
    JSON — stored as PostgreSQL JSONB for efficient querying.
    The ``is_preset`` flag marks system-provided themes that cannot be deleted.

**For QA Engineers:**
    - Only one theme per store can have ``is_active=True`` at any time.
    - Preset themes (``is_preset=True``) cannot be deleted or have their
      ``is_preset`` flag changed.
    - The ``blocks`` column stores an ordered list of page block configs.
    - Activating a theme deactivates the previously active theme.

**For End Users:**
    Themes control the look and feel of your storefront — colors, fonts,
    layout blocks, and branding. Choose from presets or create custom themes
    from the dashboard.

**For Project Managers:**
    This model supports Feature 15 (Themes) and is AI-ready — the structured
    JSON config can be generated by AI automation to create themes based on
    product genre.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class StoreTheme(Base):
    """SQLAlchemy model representing a store theme configuration.

    Attributes:
        id: Unique identifier (UUID v4).
        store_id: Foreign key linking the theme to its store.
        name: Display name of the theme (e.g., "Midnight", "My Custom Theme").
        is_active: Whether this is the currently active theme for the store.
        is_preset: Whether this is a system-provided preset (read-only).
        colors: JSON dict of OKLCH color tokens (primary, accent, background, etc.).
        typography: JSON dict of font configuration (heading_font, body_font, etc.).
        styles: JSON dict of style options (border_radius, card_style, button_style).
        blocks: JSON array of ordered page block configurations.
        logo_url: Optional URL for the store logo.
        favicon_url: Optional URL for the store favicon.
        custom_css: Optional custom CSS injected into the storefront.
        created_at: When the theme was created.
        updated_at: When the theme was last modified.
        store: Relationship back to the Store that owns this theme.
    """

    __tablename__ = "store_themes"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    store_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("stores.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_preset: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # JSON configuration columns
    colors: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    typography: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    styles: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    blocks: Mapped[list] = mapped_column(JSONB, nullable=False, default=list)

    # Branding
    logo_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    favicon_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    custom_css: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    store = relationship("Store", backref="themes", lazy="selectin")
