"""Pydantic schemas for profit analytics endpoints (Feature 13).

These schemas shape outgoing responses for the
``/api/v1/stores/{store_id}/analytics/*`` routes.

**For Developers:**
    All schemas here are response-only (no request bodies for analytics).
    ``ProfitSummaryResponse`` is the top-level KPI card data.
    ``RevenueTimeSeriesResponse`` feeds the revenue/profit chart.
    ``TopProductsResponse`` wraps the product list with period metadata.
    ``AnalyticsDashboardResponse`` bundles everything into a single call.

**For QA Engineers:**
    - ``ProfitSummaryResponse.profit_margin`` is a percentage (0.0-100.0).
    - ``RevenueTimeSeriesPoint.date`` is an ISO date string (``"YYYY-MM-DD"``).
    - ``TopProductResponse.margin`` is a percentage.
    - All monetary amounts use ``Decimal`` for precision.
    - Top-products endpoint returns ``{ period, products }`` wrapper.
    - Dashboard endpoint returns ``{ summary, revenue, top_products }``.

**For Project Managers:**
    Profit analytics are the core metric dashboard for dropshippers.
    Key KPIs: total revenue, total cost (supplier costs), gross profit,
    and profit margin. The time-series chart shows trends over selectable
    periods (7d, 30d, 90d, etc.).

**For End Users:**
    View your store's financial performance on the analytics dashboard.
    Track revenue, costs, and profit over time. See which products are
    your top earners.
"""

import uuid
from decimal import Decimal

from pydantic import BaseModel


class ProfitSummaryResponse(BaseModel):
    """Top-level profit KPIs for a given time period.

    Attributes:
        period: Time period label (e.g. ``"30d"``, ``"7d"``).
        total_revenue: Sum of all order totals in the period.
        total_cost: Sum of all supplier costs in the period.
        total_profit: Revenue minus cost.
        profit_margin: Profit as a percentage of revenue (0.0-100.0).
        total_orders: Number of completed orders in the period.
        average_order_value: Average revenue per order (revenue / orders).
        refund_total: Total refunds issued in the period.
    """

    period: str
    total_revenue: Decimal
    total_cost: Decimal
    total_profit: Decimal
    profit_margin: float
    total_orders: int
    average_order_value: Decimal
    refund_total: Decimal


class RevenueTimeSeriesPoint(BaseModel):
    """A single data point in the revenue/profit time series.

    Attributes:
        date: ISO date string (``"YYYY-MM-DD"``).
        revenue: Total revenue on this date.
        cost: Total supplier cost on this date.
        profit: Revenue minus cost on this date.
        orders: Number of orders on this date.
    """

    date: str
    revenue: Decimal
    cost: Decimal
    profit: Decimal
    orders: int


class RevenueTimeSeriesResponse(BaseModel):
    """Time-series data for the revenue/profit chart.

    Attributes:
        period: The period label these data points cover.
        data: List of daily data points.
    """

    period: str
    data: list[RevenueTimeSeriesPoint]


class TopProductResponse(BaseModel):
    """Performance data for a single top-selling product.

    Attributes:
        product_id: The product's unique identifier.
        product_title: Display title of the product.
        revenue: Total revenue generated by this product.
        cost: Total supplier cost for this product.
        profit: Revenue minus cost for this product.
        units_sold: Total units sold.
        margin: Profit margin as a percentage (0.0-100.0).
    """

    product_id: uuid.UUID
    product_title: str
    revenue: Decimal
    cost: Decimal
    profit: Decimal
    units_sold: int
    margin: float


class TopProductsResponse(BaseModel):
    """Wrapped response for the top-products endpoint.

    Contains the period and a list of top products, matching the
    expected shape ``{ period, products: [...] }``.

    Attributes:
        period: The period label for the top products query.
        products: List of top-performing products.
    """

    period: str
    products: list[TopProductResponse]


class AnalyticsDashboardResponse(BaseModel):
    """Bundled analytics dashboard data returned in a single API call.

    The dashboard combines summary KPIs, revenue time series, and
    top products into a single response. The keys are ``summary``,
    ``revenue`` (time series), and ``top_products`` (wrapped with period).

    Attributes:
        summary: Top-level profit KPIs.
        revenue: Daily revenue/profit data points for charting.
        top_products: Wrapped list of best-performing products.
    """

    summary: ProfitSummaryResponse
    revenue: RevenueTimeSeriesResponse
    top_products: TopProductsResponse
